const $=id=>document.getElementById(id);let current={azimuth:0,elevation:0},busy=false;
function sync(a,b){$(a).addEventListener('input',()=>$(b).value=$(a).value);$(b).addEventListener('input',()=>$(a).value=$(b).value)}sync('azTarget','azSlider');sync('elTarget','elSlider');
function connected(ok,msg){$('status').className='status '+(ok?'online':'offline');$('statusText').textContent=ok?'EasyComm online':'Offline';document.querySelectorAll('[data-control]').forEach(x=>x.disabled=!ok||busy);$('log').textContent=msg||'';$('log').className='log '+(ok?'':'danger')}
async function api(path,method='GET'){const r=await fetch(path,{method,cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||('HTTP '+r.status));return j}
function statusLine(j){if(j.sensor_maintenance)return 'Sensor maintenance: '+(j.sensor_maintenance_reason||'in progress');if(j.fault)return 'FAULT: '+(j.fault_reason||'unknown');let s=j.moving?'Moving':'Idle';if(j.external_feedback){s+=' | sensor '+(j.feedback_received?(j.feedback_age_ms+' ms old'):'waiting for first frame');}return s+' | backend '+j.backend}
async function refresh(){try{const j=await api('/api/status');current=j;$('azNow').textContent=j.azimuth.toFixed(1);$('elNow').textContent=j.elevation.toFixed(1);$('azFill').style.width=(j.azimuth/359*100)+'%';$('elFill').style.width=(j.elevation/180*100)+'%';connected(!j.fault,statusLine(j))}catch(e){connected(false,e.message)}}
async function command(path,label){busy=true;connected(true,label);try{await api(path,'POST');await refresh()}catch(e){connected(false,e.message)}finally{busy=false;document.querySelectorAll('[data-control]').forEach(x=>x.disabled=$('status').classList.contains('offline'))}}
$('move').onclick=()=>command('/api/move?az='+encodeURIComponent($('azTarget').value)+'&el='+encodeURIComponent($('elTarget').value),'Sending EasyComm target...');
$('stop').onclick=()=>command('/api/stop','Sending stop...');
$('park').onclick=()=>command('/api/park','Sending park target...');
$('zeroAz').onclick=()=>{if(confirm('Point the boresight north. Set current azimuth to 0/North without changing elevation?'))command('/api/zero/az','Setting current azimuth as north...')};
$('zero').onclick=()=>{if(confirm('Set both current azimuth and elevation to 0? Use Set North if you only want to zero azimuth.'))command('/api/zero','Zeroing current position...')};
$('sensorTest').onclick=async()=>{busy=true;connected(true,'Testing WT901 sensor...');try{const j=await api('/api/sensor/test','POST');current=j;const streamOk=j.sensor_stream_received&&j.sensor_stream_age_ms<1500;const mappedOk=j.feedback_received&&!j.feedback_stale&&!j.fault;const msg=(streamOk?'Sensor Stream OK':'Sensor Stream FAULT')+' | stream '+(j.sensor_stream_received?(j.sensor_stream_age_ms+' ms old'):'waiting')+' | mapped '+(mappedOk?'OK':(j.fault_reason||'not valid'))+' | az '+j.azimuth.toFixed(1)+' el '+j.elevation.toFixed(1)+' | backend '+j.motor_backend;connected(streamOk,msg);}catch(e){connected(false,e.message)}finally{busy=false;document.querySelectorAll('[data-control]').forEach(x=>x.disabled=$('status').classList.contains('offline'))}};
$('calAccel').onclick=()=>{if(confirm('Keep the WT901 level and motionless. Start accelerometer calibration now?'))command('/api/sensor/calibrate-accel','Starting WT901 accelerometer calibration...')};
$('magStart').onclick=()=>{if(confirm('Start magnetic calibration? After pressing OK, slowly rotate the sensor around all axes, then press Mag Finish/Save.'))command('/api/sensor/calibrate-magnetic-start','Starting WT901 magnetic calibration...')};
$('magFinish').onclick=()=>command('/api/sensor/calibrate-magnetic-finish','Saving WT901 magnetic calibration...');
document.querySelectorAll('[data-axis]').forEach(b=>b.onclick=()=>{let az=current.azimuth,el=current.elevation,d=Number(b.dataset.delta);if(b.dataset.axis==='az')az=(az+d+360)%360;else el=Math.max(0,Math.min(180,el+d));$('azTarget').value=$('azSlider').value=az.toFixed(1);$('elTarget').value=$('elSlider').value=el.toFixed(1);command('/api/move?az='+az.toFixed(1)+'&el='+el.toFixed(1),'Sending jog...')});
refresh();setInterval(refresh,750);
